### ISSUE TITLE
Remove Rate the App PopUp after successfully completing the third quiz for iOS 11

### ISSUE THREAD

**Issue by simonmitchell** [3sidedcube/iOS-ThunderCloud#45]
https://github.com/3sidedcube/iOS-ThunderCloud/blob/d45d0e3a4548669a1d65322e28b6e170a09ff356/ThunderCloud/TSCQuizCompletionViewController.m#L371

**Comment by simonmitchell** [comment]
This has been removed on branch `feature/swift` so we are just awaiting that being merged into Develop

**Comment by simonmitchell** [comment]
Ooops didn't mean to close and comment! 😛

**Comment by MattCheetham** [comment]
`feature/swift` has been merged
