### ISSUE TITLE
Re-write remaining code in swift

### ISSUE THREAD

**Issue by simonmitchell** [3sidedcube/iOS-ThunderCloud#65]
Most of the project has been re-written in Swift, but only due to this being a requirement for the future of `ThunderTable` development. There is still a fair amount of code left in the project that hasn't been re-written in swift because it wasn't necessary (Either because it didn't need to be swiftified, or because it didn't need re-writting like quizzes).

Would be good to get the rest of the code re-written as we go

**Comment by MattCheetham** [comment]
This ticket is vague and difficult to action. Consider breaking it down into more specific tickets such as "re-write x object in Swift" or "re-write <feature> in Swift. Then we can quantify progress better.

**Comment by simonmitchell** [comment]
Yeah you're right. Shall do!
